"""
GitHub Integration Architecture & CI Workflow Annotation Module.
Provides GitHub PR payload generation, inline comments, and GitHub Actions workflow annotation outputs.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from app.ai.base import ReviewIssue


class GitHubPullRequestComment(BaseModel):
    """Represents an inline PR code review comment for GitHub REST/GraphQL API."""
    path: str
    line: Optional[int]
    side: str = "RIGHT"
    body: str


class GitHubPRReviewPayload(BaseModel):
    """Complete PR review submission payload for GitHub API."""
    pr_number: int
    commit_id: Optional[str]
    event: str = Field(default="COMMENT", description="APPROVE, REQUEST_CHANGES, COMMENT")
    body: str
    comments: List[GitHubPullRequestComment] = []


def format_github_actions_annotation(issue: ReviewIssue) -> str:
    """
    Format a ReviewIssue into a GitHub Actions workflow annotation string.
    Syntax: ::(warning|error) file={file},line={line},title={title}::{description}
    """
    annotation_type = "error" if issue.severity == "HIGH" else "warning"
    line_attr = f",line={issue.line_number}" if issue.line_number else ""
    title_escaped = issue.title.replace("\n", " ").replace(":", "%3A")
    desc_escaped = issue.description.replace("\n", "%0A")

    return f"::{annotation_type} file={issue.file_path}{line_attr},title={title_escaped}::{desc_escaped}"


class GitHubIntegrationEngine:
    """
    Architecture helper to format CodeReview Agent findings into GitHub PR review comments.
    """

    def __init__(self, repo_full_name: Optional[str] = None, github_token: Optional[str] = None):
        self.repo_full_name = repo_full_name
        self.github_token = github_token

    def format_inline_comment(self, issue: ReviewIssue) -> GitHubPullRequestComment:
        """Convert a ReviewIssue into a GitHub inline review comment."""
        severity_emoji = {
            "HIGH": "🚨 **HIGH SEVERITY**",
            "MEDIUM": "⚠️ **MEDIUM SEVERITY**",
            "LOW": "ℹ️ **LOW SEVERITY**",
            "INFO": "💡 **NOTE**",
        }
        prefix = severity_emoji.get(issue.severity.upper(), issue.severity)

        code_example_block = f"\n\n**Suggested Fix Example:**\n```\n{issue.code_example}\n```" if issue.code_example else ""

        body = (
            f"{prefix}: **{issue.title}**\n\n"
            f"{issue.description}\n\n"
            f"**Actionable Fix:**\n"
            f"{issue.suggestion}"
            f"{code_example_block}\n\n"
            f"*Generated by CodeReview Agent AI (Fix Time: ~{issue.estimated_fix_minutes}m, Confidence: {issue.confidence_score*100:.0f}%)*"
        )

        return GitHubPullRequestComment(
            path=issue.file_path,
            line=issue.line_number or 1,
            body=body,
        )

    def create_pr_review_payload(
        self,
        pr_number: int,
        issues: List[ReviewIssue],
        overall_score: float,
        commit_id: Optional[str] = None,
    ) -> GitHubPRReviewPayload:
        """Construct full PR review payload with summary and inline comments."""
        comments = [self.format_inline_comment(issue) for issue in issues]

        high_count = sum(1 for i in issues if i.severity == "HIGH")
        event = "REQUEST_CHANGES" if high_count > 0 or overall_score < 7.0 else "COMMENT"

        summary_body = (
            f"## 🤖 CodeReview Agent Automated PR Review\n\n"
            f"- **Overall Health Score:** `{overall_score}/10.0`\n"
            f"- **Total Issues Found:** `{len(issues)}`\n"
            f"- **High Severity Issues:** `{high_count}`\n\n"
            f"{'❌ Changes requested due to security/high-severity risks.' if event == 'REQUEST_CHANGES' else '✅ Automated review completed cleanly.'}"
        )

        return GitHubPRReviewPayload(
            pr_number=pr_number,
            commit_id=commit_id,
            event=event,
            body=summary_body,
            comments=comments,
        )
